version: "3.7"

services:
  app:
    build: .
    container_name: asksuite-test
    environment:
      - BROWSER_PATH=/usr/bin/chromium-browser
    ports: 
      - 8080:8080
    volumes:
      - .:/usr/app